## Name: Fortune Obiora Chiagozie
## Hamoye ID: 11c2f4fe9401f000

In [1]:
import numpy as np
import pandas as pd

In [8]:
food_data = pd.read_csv("FoodBalanceSheets_E_Africa_NOFLAG.csv", encoding='latin-1')

In [9]:
food_data

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28
5,4,Algeria,2903,Vegetal Products,664,Food supply (kcal/capita/day),kcal/capita/day,2932.00,2958.00,2941.00,2921.00,2932.00
6,4,Algeria,2903,Vegetal Products,674,Protein supply quantity (g/capita/day),g/capita/day,67.14,67.38,67.37,66.11,67.10
7,4,Algeria,2903,Vegetal Products,684,Fat supply quantity (g/capita/day),g/capita/day,53.84,54.72,52.04,55.59,54.57
8,4,Algeria,2941,Animal Products,664,Food supply (kcal/capita/day),kcal/capita/day,444.00,421.00,431.00,421.00,390.00
9,4,Algeria,2941,Animal Products,674,Protein supply quantity (g/capita/day),g/capita/day,27.76,26.97,27.35,26.71,24.73
10,4,Algeria,2941,Animal Products,684,Fat supply quantity (g/capita/day),g/capita/day,26.22,24.64,25.37,24.60,22.71
11,4,Algeria,2905,Cereals - Excluding Beer,5511,Production,1000 tonnes,3436.00,3761.00,3445.00,3478.00,6065.00
12,4,Algeria,2905,Cereals - Excluding Beer,5611,Import Quantity,1000 tonnes,12604.00,13983.00,13523.00,13039.00,13182.00
13,4,Algeria,2905,Cereals - Excluding Beer,5072,Stock Variation,1000 tonnes,684.00,1663.00,905.00,705.00,2226.00
14,4,Algeria,2905,Cereals - Excluding Beer,5911,Export Quantity,1000 tonnes,3.00,7.00,7.00,10.00,17.00
15,4,Algeria,2905,Cereals - Excluding Beer,5301,Domestic supply quantity,1000 tonnes,15353.00,16075.00,16056.00,15803.00,17004.00
16,4,Algeria,2905,Cereals - Excluding Beer,5521,Feed,1000 tonnes,4725.00,5070.00,4838.00,4667.00,5266.00
17,4,Algeria,2905,Cereals - Excluding Beer,5527,Seed,1000 tonnes,177.00,189.00,197.00,202.00,278.00
18,4,Algeria,2905,Cereals - Excluding Beer,5123,Losses,1000 tonnes,1084.00,1203.00,1148.00,1121.00,1253.00
19,4,Algeria,2905,Cereals - Excluding Beer,5131,Processing,1000 tonnes,35.00,38.00,37.00,33.00,44.00
20,4,Algeria,2905,Cereals - Excluding Beer,5154,Other uses (non-food),1000 tonnes,787.00,847.00,835.00,840.00,951.00
21,4,Algeria,2905,Cereals - Excluding Beer,5170,Residuals,1000 tonnes,0.00,0.00,0.00,0.00,-8.00
22,4,Algeria,2905,Cereals - Excluding Beer,5142,Food,1000 tonnes,8546.00,8729.00,9001.00,8941.00,9219.00
23,4,Algeria,2905,Cereals - Excluding Beer,645,Food supply quantity (kg/capita/yr),kg,219.56,219.72,221.98,216.02,218.31
24,4,Algeria,2905,Cereals - Excluding Beer,664,Food supply (kcal/capita/day),kcal/capita/day,1680.00,1682.00,1699.00,1656.00,1672.00
25,4,Algeria,2905,Cereals - Excluding Beer,674,Protein supply quantity (g/capita/day),g/capita/day,49.43,49.54,50.01,48.86,49.36
26,4,Algeria,2905,Cereals - Excluding Beer,684,Fat supply quantity (g/capita/day),g/capita/day,6.84,6.78,6.83,6.63,6.58
27,4,Algeria,2511,Wheat and products,5511,Production,1000 tonnes,2436.00,2657.00,2440.00,2437.00,3981.00
28,4,Algeria,2511,Wheat and products,5611,Import Quantity,1000 tonnes,7461.00,8531.00,8255.00,8105.00,8434.00
29,4,Algeria,2511,Wheat and products,5072,Stock Variation,1000 tonnes,487.00,1401.00,731.00,546.00,1927.00
...,...,...,...,...,...,...,...,...,...,...,...,...
60913,181,Zimbabwe,2928,Miscellaneous,5611,Import Quantity,1000 tonnes,42.00,47.00,34.00,15.00,16.00
60914,181,Zimbabwe,2928,Miscellaneous,5072,Stock Variation,1000 tonnes,0.00,0.00,0.00,-4.00,0.00
60915,181,Zimbabwe,2928,Miscellaneous,5911,Export Quantity,1000 tonnes,1.00,1.00,1.00,1.00,1.00
60916,181,Zimbabwe,2928,Miscellaneous,5301,Domestic supply quantity,1000 tonnes,41.00,46.00,33.00,19.00,16.00
60917,181,Zimbabwe,2928,Miscellaneous,5170,Residuals,1000 tonnes,0.00,0.00,0.00,0.00,0.00
60918,181,Zimbabwe,2928,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60919,181,Zimbabwe,2928,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.34,1.09
60920,181,Zimbabwe,2928,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,2.00,1.00
60921,181,Zimbabwe,2928,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.05,0.04
60922,181,Zimbabwe,2928,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.02
60923,181,Zimbabwe,2680,Infant food,5611,Import Quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
60924,181,Zimbabwe,2680,Infant food,5072,Stock Variation,1000 tonnes,0.00,0.00,0.00,0.00,0.00
60925,181,Zimbabwe,2680,Infant food,5911,Export Quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
60926,181,Zimbabwe,2680,Infant food,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
60927,181,Zimbabwe,2680,Infant food,5170,Residuals,1000 tonnes,0.00,0.00,0.00,0.00,0.00
60928,181,Zimbabwe,2680,Infant food,5142,Food,1000 tonnes,0.00,0.00,0.00,0.00,0.00
60929,181,Zimbabwe,2680,Infant food,645,Food supply quantity (kg/capita/yr),kg,0.00,0.00,0.00,0.00,0.01
60930,181,Zimbabwe,2680,Infant food,664,Food supply (kcal/capita/day),kcal/capita/day,0.00,0.00,0.00,0.00,0.00
60931,181,Zimbabwe,2680,Infant food,674,Protein supply quantity (g/capita/day),g/capita/day,0.00,0.00,0.00,0.00,0.00
60932,181,Zimbabwe,2680,Infant food,684,Fat supply quantity (g/capita/day),g/capita/day,0.00,0.00,0.00,0.00,0.00
60933,181,Zimbabwe,2899,Miscellaneous,5611,Import Quantity,1000 tonnes,42.00,47.00,33.00,15.00,16.00
60934,181,Zimbabwe,2899,Miscellaneous,5072,Stock Variation,1000 tonnes,0.00,0.00,0.00,-4.00,0.00
60935,181,Zimbabwe,2899,Miscellaneous,5911,Export Quantity,1000 tonnes,1.00,1.00,0.00,0.00,1.00
60936,181,Zimbabwe,2899,Miscellaneous,5301,Domestic supply quantity,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60937,181,Zimbabwe,2899,Miscellaneous,5170,Residuals,1000 tonnes,0.00,0.00,0.00,0.00,0.00
60938,181,Zimbabwe,2899,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60939,181,Zimbabwe,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.33,1.08
60940,181,Zimbabwe,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,1.00,1.00
60941,181,Zimbabwe,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.04,0.04
60942,181,Zimbabwe,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.01

In [10]:
food_data.groupby('Item').sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Item,,,,,,,,
"Alcohol, Non-Food",38447,752497,1515090,2403.00,2180.00,2223.00,2348.00,2293.00
Alcoholic Beverages,75016,1649136,2171381,102410.11,98783.72,96958.75,95581.06,97847.27
Animal Products,18060,397035,90990,11935.65,11811.73,11661.69,11547.65,11578.61
Animal fats,85279,1882494,2567303,209460.54,200675.72,183314.22,269617.53,269648.27
Apples and products,69280,1352989,1920418,9499.23,10559.15,9853.26,10198.90,9640.51
"Aquatic Animals, Others",47420,966381,1139179,14.55,9.26,6.17,5.92,5.92
Aquatic Plants,51178,1057275,1278386,507.29,631.23,470.21,452.02,452.02
"Aquatic Products, Other",52570,1160712,1320249,519.62,638.42,475.08,456.65,456.65
Bananas,68496,1338880,1894890,53267.31,55046.76,54376.07,53008.82,55549.23
Barley and products,76321,1432410,2243002,25384.66,29153.44,24706.08,26176.98,31253.70
Beans,78001,1476680,2263509,19207.68,20315.77,19037.50,21351.42,20121.14
Beer,65975,1314720,1813728,41879.92,42053.67,42540.48,41962.92,41612.12
"Beverages, Alcoholic",65918,1313052,1807946,3067.16,2818.38,2834.92,3115.24,2979.21
"Beverages, Fermented",65203,1299273,1774758,50536.78,47447.92,45478.53,43958.75,46874.94
Bovine Meat,70033,1431044,1963251,22098.60,22766.42,22411.18,22612.86,23926.30
"Butter, Ghee",60516,1238480,1594919,1249.29,1165.69,1199.87,1116.68,1175.59
Cassava and products,73208,1385004,2081916,405442.57,410235.89,415730.20,401440.17,435862.14
Cephalopods,58593,1233636,1571763,423.03,496.95,503.64,532.14,532.07
Cereals - Excluding Beer,95370,2074170,2976719,851924.06,845669.36,875974.56,905221.25,903280.79
"Cereals, Other",79505,1489320,2326237,18689.11,18912.55,19877.56,20615.95,22125.96
"Citrus, Other",70239,1367122,1954812,14533.46,15188.91,15515.30,15650.97,15804.14
Cloves,53398,1064726,1420590,77.37,77.29,78.27,82.32,82.36
Cocoa Beans and products,70862,1398123,1998287,7166.65,7671.59,7510.86,8638.32,8353.83
Coconut Oil,69418,1330248,1959863,517.56,556.18,549.43,516.99,537.70
Coconuts - Incl Copra,74263,1410560,2104761,6568.33,6646.28,6577.23,6478.91,6526.12
Coffee and products,72724,1433350,2070618,3677.92,3849.99,4115.34,3861.45,4009.65
Cottonseed,44285,841911,1768564,8108.00,7998.00,8093.00,8623.00,8802.00
Cottonseed Oil,67319,1287500,1881106,1379.76,1507.90,1366.75,1403.25,1421.56
Cream,55778,1141088,1421946,237.52,233.37,267.84,228.95,271.61
Crustaceans,64831,1338260,1761859,734.07,732.86,717.30,834.82,833.61
...,...,...,...,...,...,...,...,...
Rye and products,63769,1192110,1788655,284.24,428.14,303.19,306.41,324.35
Sesame seed,71143,1365013,2121769,8044.24,6769.62,7819.98,7955.60,8492.35
Sesameseed Oil,65744,1230183,1814000,609.73,587.58,716.58,663.10,589.79
Sorghum and products,84070,1525908,2456864,86939.64,82725.53,91609.56,85468.93,91504.28
Soyabean Oil,70775,1362630,1986336,9033.32,10381.77,10151.87,10683.31,11422.03
Soyabeans,76891,1456350,2225300,15067.19,16412.47,15920.30,18574.99,24180.95
Spices,70582,1522883,1945922,4421.98,5059.08,6839.95,6801.63,6406.66
"Spices, Other",66306,1296050,1783586,1695.48,2068.57,3692.79,3744.19,3318.96
Starchy Roots,90330,1959318,2763138,792393.91,802578.22,823223.18,825497.34,855955.18
Stimulants,75449,1656774,2186289,13587.83,14180.97,14314.71,15119.56,15214.78
Sugar & Sweeteners,82006,1783217,2435532,78235.83,80214.74,80920.20,86952.63,87663.08
Sugar (Raw Equivalent),70517,1352344,2004572,69295.13,70675.27,71786.18,77413.80,78055.95
Sugar Crops,66146,1445276,2127345,322467.52,317423.30,314772.13,315572.36,326132.77
Sugar beet,33784,616491,1108508,40090.00,47240.00,47244.00,45332.00,44685.00
Sugar cane,59554,1133592,1913174,282380.51,270179.30,267526.12,270238.36,281447.76
Sugar non-centrifugal,18769,307461,526787,236.98,230.85,185.80,204.68,215.68
Sunflower seed,57326,999787,1677799,11136.14,10686.98,6749.09,7545.63,7500.39
Sunflowerseed Oil,70253,1348252,1957077,6126.70,4986.00,4901.51,6432.42,5996.97
Sweet potatoes,74062,1393150,2131142,68785.44,67762.36,69849.89,76488.54,77209.90
"Sweeteners, Other",77144,1464768,2244222,8034.54,8593.45,8277.40,8667.08,8701.86
Tea (including mate),65694,1280610,1759540,2716.24,2627.37,2652.44,2599.72,2834.23
Tomatoes and products,74112,1440954,2117921,68147.92,68981.37,62570.48,61712.96,63750.78
Treenuts,70304,1525888,1962812,6523.47,6939.31,6319.69,6875.08,6886.56
Vegetable Oils,76734,1675550,2228663,59740.35,60659.38,58312.01,67913.02,68401.90
Vegetables,78335,1712866,2295933,256648.34,264068.13,256219.45,259140.62,268337.49
"Vegetables, Other",77779,1518715,2275409,155038.96,158104.08,156218.90,157752.59,163987.21
Vegetal Products,18060,391905,90990,107145.19,107064.17,106792.72,107655.20,107775.39
Wheat and products,87073,1639683,2654934,232670.13,234710.51,239377.07,240047.62,242645.19
Wine,66206,1319535,1818328,4497.36,4251.81,3872.09,4178.02,4039.32
Yams,50798,970905,1525745,200396.96,203151.78,220626.20,229174.59,221272.09

In [13]:
food_data.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [15]:
food_data.isnull().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [17]:
food_data.shape()

TypeError: 'tuple' object is not callable

In [18]:
food_data.groupby('Element').sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,
Domestic supply quantity,708993,14197445,28068795,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,11840553,26026133,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,13535000,3435732,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,3538507,7282199,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,13285035,25406622,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,13511060,3329296,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,13185401,3163725,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,13795966,28834929,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,5424803,10292107,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,4729749,8926728,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,5350416,10313310,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,10450053,21388191,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,13535000,3385502,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,12421089,24066350,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,2035933,4211574,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,11329527,21464704,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,112545,22995,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,1486528,2869905,416.00,349.00,89.00,91.00,90.00

In [30]:
food_data[['Y2018','Element']].groupby('Element').sum().sort_values(by = 'Y2018')

                                             Y2018
Element
Tourist consumption                          90.00
Fat supply quantity (g/capita/day)        10258.69
Protein supply quantity (g/capita/day)    11833.56
Stock Variation                           20577.91
Seed                                      25263.14
Residuals                                 34864.00
Food supply quantity (kg/capita/yr)       49056.85
Other uses (non-food)                     91300.97
Losses                                   163902.00
Export Quantity                          181594.80
Feed                                     233489.68
Import Quantity                          287997.09
Processing                               308429.00
Food supply (kcal/capita/day)            455261.00
Total Population - Both sexes           1140605.00
Food                                    1303841.28
Production                              2075072.89
Domestic supply quantity                2161192.10

In [32]:
food_data['Area'].value_counts()

Kenya                          1560
Egypt                          1488
Nigeria                        1474
Côte d'Ivoire                  1467
Senegal                        1462
Cameroon                       1460
Uganda                         1458
Zambia                         1451
Malawi                         1447
Ethiopia                       1447
Madagascar                     1439
Mozambique                     1427
Rwanda                         1426
Angola                         1424
United Republic of Tanzania    1419
Congo                          1413
Guinea                         1410
Burkina Faso                   1409
Niger                          1403
South Africa                   1399
Zimbabwe                       1393
Morocco                        1393
Mauritius                      1378
Botswana                       1378
Ghana                          1354
Central African Republic       1344
Chad                           1343
Tunisia                        1338
Sudan                          1316
Algeria                        1313
Togo                           1294
Mali                           1293
Benin                          1285
Eswatini                       1284
Namibia                        1283
Cabo Verde                     1260
Gabon                          1245
Sierra Leone                   1242
Liberia                        1206
Mauritania                     1195
Sao Tome and Principe          1177
Gambia                         1168
Lesotho                        1150
Guinea-Bissau                  1128
Djibouti                       1095
Seychelles                       68
Sudan (former)                   53
Comoros                          45
Ethiopia PDR                     39
Name: Area, dtype: int64